# Generated by Django 6.0.3 on 2026-03-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonised System code required for EUDR due diligence statement (e.g. 1201 for soya beans).', max_length=20),
        ),
    ]
