# Generated by Django 6.0.3 on 2026-03-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eu_novel_food_ref',
            field=models.CharField(blank=True, help_text='EU Novel Food approval reference (e.g. Commission Decision 2008/575/EC for baobab).', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='eu_novel_food_status',
            field=models.BooleanField(blank=True, help_text='Is this product approved under EU Novel Food Regulation (EU) 2015/2283? Applies to baobab fruit pulp (approved 2008).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nafdac_registration_number',
            field=models.CharField(blank=True, help_text='NAFDAC registration or export notification number. Required for processed food/agricultural products.', max_length=50),
        ),
    ]
