# Generated by Django 6.0.3 on 2026-04-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_add_access_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='commodity',
            field=models.CharField(blank=True, choices=[('cocoa', 'Cocoa'), ('coffee', 'Coffee'), ('soy', 'Soy'), ('palm_oil', 'Palm Oil'), ('multiple', 'Multiple commodities'), ('other', 'Other')], max_length=20),
        ),
    ]
