[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn agri_ops_project.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120 --log-level debug"
healthcheckPath = "/login/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
