# Generated by Django 6.0.3 on 2026-03-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nepc_registration_expiry',
            field=models.DateField(blank=True, help_text='NEPC registration expiry date.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nepc_registration_number',
            field=models.CharField(blank=True, help_text='Nigerian Export Promotion Council registration number. Required before any export transaction.', max_length=50),
        ),
    ]
