# Generated by Django 6.0.3 on 2026-03-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_nepc_registration_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
