# Generated by Django 6.0.3 on 2026-03-13 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('equipment', 'Equipment'), ('livestock_feed', 'Livestock Feed'), ('chemicals', 'Chemicals'), ('packaging', 'Packaging'), ('cooperative', 'Cooperative'), ('processor', 'Processor'), ('distributor', 'Distributor'), ('exporter', 'Exporter'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('farmer_name', models.CharField(blank=True, max_length=255)),
                ('geolocation', models.JSONField(blank=True, help_text='GeoJSON Polygon. Export from SW Maps or NCAN Farm Mapper.', null=True)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state_region', models.CharField(blank=True, max_length=100)),
                ('commodity', models.CharField(help_text='e.g. Soy, Maize, Cocoa', max_length=100)),
                ('deforestation_risk_status', models.CharField(choices=[('low', 'Low Risk'), ('standard', 'Standard Risk'), ('high', 'High Risk')], default='standard', max_length=20)),
                ('mapping_date', models.DateField(blank=True, null=True)),
                ('is_eudr_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('verification_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='companies.company')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms_mapped', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='suppliers.supplier')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('farm_map', 'Farm Map'), ('satellite_image', 'Satellite Image'), ('land_registry', 'Land Registry'), ('certification', 'Third-Party Certification'), ('declaration', 'Farmer Declaration'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='compliance_docs/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_docs', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.farm')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
