# Generated by Django 6.0.3 on 2026-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_add_farm_compliance_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='reliability_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reliability score 0-10. Updated based on delivery history.', max_digits=4, null=True),
        ),
    ]
