# Generated by Django 6.0.3 on 2026-03-22 07:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_add_reliability_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='deforestation_reference_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 31), help_text='Date of the evidence baseline for deforestation status. Must be on or before 31 Dec 2020 for EUDR compliance.', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='harvest_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Most recent harvest year on this plot (e.g. 2024). Required for EUDR due diligence statement.', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='land_cleared_after_cutoff',
            field=models.BooleanField(blank=True, help_text='Was this land cleared or subject to deforestation after 31 December 2020? Yes = disqualified from EUDR.', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='reliability_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reliability score 0-10. Updated based on delivery history.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
