# Generated by Django 6.0.3 on 2026-03-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_nepc_registration_expiry_and_more'),
        ('suppliers', '0004_farm_deforestation_reference_date_farm_harvest_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('organic_eu', 'Organic EU (2018/848)'), ('globalgap', 'GlobalG.A.P.'), ('fairtrade', 'Fairtrade'), ('rainforest_alliance', 'Rainforest Alliance'), ('iscc', 'ISCC (Sustainability & Carbon)'), ('other', 'Other')], max_length=30)),
                ('certifying_body', models.CharField(help_text='e.g. ECOCERT, Control Union, SGS', max_length=255)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_certifications', to='companies.company')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='suppliers.farm')),
            ],
            options={
                'ordering': ['cert_type'],
            },
        ),
    ]
