# Generated by Django 6.0.3 on 2026-03-23 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_farmcertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='area_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
