# Generated by Django 6.0.3 on 2026-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_farm_import_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='fvf_consent_date',
            field=models.DateField(blank=True, help_text='Date the farmer signed the FVF consent (ties digital record to paper).', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='fvf_consent_given',
            field=models.BooleanField(default=False, help_text='Farmer has signed the FVF consent block. Paper form is on file.'),
        ),
        migrations.AddField(
            model_name='farm',
            name='fvf_expansion_intent',
            field=models.BooleanField(blank=True, help_text='To expand, would the farmer cut trees? (forward deforestation risk)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='fvf_land_acquisition',
            field=models.CharField(blank=True, choices=[('inherited', 'Inherited'), ('bought', 'Bought from neighbour'), ('granted', 'Granted by local leader')], help_text='How did the farmer acquire this land?', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='fvf_land_tenure',
            field=models.CharField(blank=True, choices=[('title_deed', 'Title Deed'), ('village_consent', 'Village Consent')], help_text='Does the farmer hold a title deed or village consent?', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='fvf_untouched_forest',
            field=models.BooleanField(blank=True, help_text='Is there any untouched forest remaining on this property?', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='fvf_years_farming',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many years has the farmer been planting on this plot?', null=True),
        ),
    ]
