# Generated by Django 6.0.3 on 2026-04-17 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_plan_tier'),
        ('suppliers', '0012_farmimportlog_auto_corrected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['company', 'is_eudr_verified'], name='farm_company_eudr_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['company', 'commodity'], name='farm_company_commodity_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['company', 'deforestation_risk_status'], name='farm_company_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['company', 'supplier'], name='farm_company_supplier_idx'),
        ),
    ]
