# Generated by Django 6.0.3 on 2026-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_farm_farm_company_eudr_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmimportlog',
            name='transformation_log',
            field=models.JSONField(default=list),
        ),
    ]
