# Generated by Django 6.0.3 on 2026-04-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_transformation_log_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='suppliers.supplier'),
        ),
    ]
