# Generated by Django 6.0.3 on 2026-04-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_farm_supplier_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='mapped_by_name',
            field=models.CharField(blank=True, default='', help_text='Field officer name as recorded in the import file (free text — not a platform user).', max_length=150),
        ),
    ]
