# Generated by Django 6.0.3 on 2026-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_farm_mapped_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='geometry_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the canonical geolocation JSON. Immutability verification.', max_length=64),
        ),
    ]
