# Generated by Django 6.0.3 on 2026-04-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_farm_geometry_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='raw_geolocation',
            field=models.JSONField(blank=True, help_text='Original pre-normalisation geometry from the import file. Null when geometry was not modified or farm was created manually.', null=True),
        ),
    ]
