# Generated by Django 6.0.5 on 2026-05-13 22:23

import apps.suppliers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_plan_tier'),
        ('suppliers', '0018_add_raw_geolocation_to_farm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='file',
            field=models.FileField(upload_to='compliance_docs/%Y/%m/', validators=[apps.suppliers.models.validate_compliance_file]),
        ),
        migrations.CreateModel(
            name='DeforestationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='Hansen GFC', max_length=100)),
                ('dataset_version', models.CharField(default='v1.12', max_length=20)),
                ('treecover_threshold', models.PositiveSmallIntegerField(default=10)),
                ('cutoff_year', models.PositiveSmallIntegerField(default=2020)),
                ('total_pixels', models.PositiveIntegerField(blank=True, null=True)),
                ('post_cutoff_loss_pixels', models.PositiveIntegerField(blank=True, null=True)),
                ('post_cutoff_loss_area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('loss_years_detected', models.JSONField(default=list)),
                ('risk_status', models.CharField(choices=[('clear', 'Clear'), ('flagged', 'Flagged'), ('inconclusive', 'Inconclusive'), ('error', 'Error')], max_length=20)),
                ('engine_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=20)),
                ('evidence_summary', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('geometry_hash_at_assessment', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deforestation_checks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deforestation_checks', to='companies.company')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deforestation_checks', to='suppliers.farm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', '-created_at'], name='defcheck_farm_date_idx'), models.Index(fields=['company', 'risk_status'], name='defcheck_company_risk_idx')],
            },
        ),
    ]
