# Generated by Django 6.0.5 on 2026-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0019_deforestationcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='land_cleared_after_cutoff_reason',
            field=models.TextField(blank=True, default='', help_text="Manager's basis for manually overriding the deforestation engine's disqualification result. Required whenever the override is set."),
        ),
        migrations.AlterField(
            model_name='farm',
            name='land_cleared_after_cutoff',
            field=models.BooleanField(blank=True, help_text='Manual disqualification override. Leave blank to defer to the deforestation engine. Set to Yes/No only to override the engine result — a reason is required when set.', null=True),
        ),
    ]
