# Generated by Django 6.0.3 on 2026-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='Display title within the organisation. No permission bearing.', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='system_role',
            field=models.CharField(choices=[('org_admin', 'Organisation Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', help_text='Controls permissions. Never accept from user input directly.', max_length=30),
        ),
    ]
