# Generated by Django 6.0.3 on 2026-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lot_number',
            field=models.CharField(blank=True, help_text='e.g. FN-2026-004. Auto-generated if left blank.', max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='moisture_content',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moisture percentage at time of intake', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='origin_state',
            field=models.CharField(blank=True, help_text='State or region of origin e.g. Benue, Kano', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Standard'), ('C', 'Grade C — Below Standard'), ('off', 'Off Grade')], help_text='Quality grade assigned at intake inspection', max_length=10),
        ),
    ]
