# Generated by Django 6.0.3 on 2026-04-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_plan_tier'),
        ('inventory', '0002_add_commodity_fields'),
        ('products', '0003_product_eu_novel_food_ref_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company', 'product'], name='inv_company_product_idx'),
        ),
    ]
