# Generated by Django 6.0.3 on 2026-04-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_plan_tier'),
        ('purchase_orders', '0001_initial'),
        ('suppliers', '0012_farmimportlog_auto_corrected'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', '-order_date'], name='po_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'status'], name='po_company_status_idx'),
        ),
    ]
