# Generated by Django 6.0.3 on 2026-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_plan_tier'),
        ('purchase_orders', '0002_purchaseorder_po_company_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('company', 'order_number')},
        ),
    ]
