# Generated by Django 6.0.3 on 2026-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_create_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('import', 'Import')], max_length=10),
        ),
    ]
