# Generated by Django 6.0.3 on 2026-03-18 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('sales_orders', '0002_initial'),
        ('suppliers', '0003_add_reliability_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('commodity', models.CharField(max_length=100)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='companies.company')),
                ('farms', models.ManyToManyField(blank=True, related_name='batches', to='suppliers.farm')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='sales_orders.salesorder')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
