# Generated by Django 6.0.3 on 2026-03-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0003_add_batch_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked batches cannot be deleted. Set automatically on dispatch; manual lock also supported.'),
        ),
        migrations.AddField(
            model_name='batch',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net mass in kilograms — required for EUDR due diligence statement (Article 9).', max_digits=12, null=True),
        ),
    ]
