# Generated by Django 6.0.3 on 2026-03-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_nepc_registration_expiry_and_more'),
        ('sales_orders', '0004_batch_is_locked_batch_quantity_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='certificate_of_origin_ref',
            field=models.CharField(blank=True, help_text='Certificate of Origin reference number issued by Nigerian Chamber of Commerce / Customs.', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='nxp_reference',
            field=models.CharField(blank=True, help_text='CBN Form NXP reference number — registers export proceeds obligation with authorised dealer bank.', max_length=50),
        ),
        migrations.CreateModel(
            name='BatchQualityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('mrl', 'Pesticide MRL (EU 396/2005)'), ('aflatoxin', 'Aflatoxin (EU 1881/2006)'), ('moisture', 'Moisture Content'), ('heavy_metals', 'Heavy Metals'), ('microbiological', 'Microbiological'), ('other', 'Other')], max_length=30)),
                ('lab_name', models.CharField(max_length=255)),
                ('lab_certificate_ref', models.CharField(blank=True, max_length=100)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass — within limits'), ('fail', 'Fail — exceeds limits'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='sales_orders.batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_quality_tests', to='companies.company')),
            ],
            options={
                'verbose_name': 'Batch Quality Test',
                'ordering': ['-test_date', 'test_type'],
            },
        ),
        migrations.CreateModel(
            name='PhytosanitaryCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('issuing_office', models.CharField(blank=True, help_text='NAQS zonal office that issued the certificate (e.g. NAQS Apapa Seaport)', max_length=255)),
                ('inspector_name', models.CharField(blank=True, max_length=255)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phytosanitary_certs', to='sales_orders.batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phytosanitary_certs', to='companies.company')),
            ],
            options={
                'verbose_name': 'Phytosanitary Certificate',
                'ordering': ['-created_at'],
            },
        ),
    ]
