# Generated by Django 6.0.3 on 2026-03-23 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0005_salesorder_certificate_of_origin_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net mass in kilograms — required for EUDR due diligence statement (Article 9).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
