# Generated by Django 6.0.3 on 2026-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0006_alter_batch_quantity_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='is_eu_export',
            field=models.BooleanField(default=False, help_text='Flag for EU-bound shipments. Enables EUDR compliance sections on traceability certificate.'),
        ),
    ]
