# Generated by Django 6.0.3 on 2026-04-17 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_plan_tier'),
        ('sales_orders', '0007_salesorder_is_eu_export'),
        ('suppliers', '0012_farmimportlog_auto_corrected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['company', '-created_at'], name='batch_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['company', 'commodity'], name='batch_company_commodity_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['is_locked'], name='batch_locked_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', '-order_date'], name='so_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'status'], name='so_company_status_idx'),
        ),
    ]
