# Generated by Django 6.0.3 on 2026-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_fix_order_number_tenant_uniqueness'),
        ('sales_orders', '0009_fix_order_number_tenant_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, related_name='batches', to='purchase_orders.purchaseorder'),
        ),
    ]
