# Generated by Django 6.0.3 on 2026-03-18 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ops_login', 'Ops Login'), ('ops_login_failed', 'Ops Login Failed'), ('ops_logout', 'Ops Logout'), ('otp_setup', 'OTP Setup'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='ops_dashboa_timesta_a98ddb_idx'), models.Index(fields=['event', '-timestamp'], name='ops_dashboa_event_128a01_idx')],
            },
        ),
    ]
